### ISSUE TITLE
UseDimensionsReturn get the generic type given to useDimesions

### ISSUE THREAD

**Issue by mmussmann** [DZakh-packages/react-hook-dimensions#4]
On line 39 in index.ts there should be a generic passed to the return type.

**Current**
`}: UseDimensionsOptions = {}): UseDimensionsReturn {`

**Expected**
`}: UseDimensionsOptions = {}): UseDimensionsReturn<TElement> {`

In it's current state the DimensionsRef<TElement> always ends up as HTMLElement

**Comment by DZakh** [comment]
Thanks for the issue. I'll publish the fixed version in the near future.
